# Site settings
title: BCN data
header-img: img/bunkers_tilt_low.jpg
email: joebrew@gmail.com
description: "BCN data"
url: "http://bcndata.github.io"
twitter_username: bcndata
github_username:  bcndata
facebook_username:  bcndata

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
