# Site settings
title: BCN data
header-img: img/roofs.JPG
email: joebrew@gmail.com
description: "BCN data"
url: "http://yourdomain.com"
twitter_username: bcndata
github_username:  bcndata
facebook_username:  bcndata

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
